checks:
    javascript: true

build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - eslint-run src
    coverage:
      tests:
        override:
          - command: npm run test
            coverage:
              file: coverage/coverage.json
              format: lcov

filter:
  excluded_paths:
    - tests/*
